[package]
name = "crun"
version = "0.1.0"
edition = "2021"

[dependencies]
rofi-mode = "0.4.1"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.122"

[lib]
crate-type = ["cdylib"]
